name: py3.6.10-ai-base
channels:
- conda-forge
- defaults
dependencies:
- python=3.6.10
- pip=20.0.2
- numpy=1.18.1
- pandas=1.0.1
- sqlalchemy=1.3.13
- pyhdb=0.3.4
- scipy=1.4.1
- scikit-learn=0.22.1
- tensorflow=2.1.0
- matplotlib=3.1.3
- jupyter=1.0.0
- jupyterlab=1.2.6
